[net]
max_connections = 256
pvs_range = 20.0
pvs_priority_range = 30.0
tickrate = 60

[game]
maxplayers = 150
soft_max_players = 100
hostname = "🌒 Project Eclipse - ФРОНТИР! [18+] 🌒"
desc = "💎Начни свое путешествие на секторе ЭКЛИПС прямо сейчас!\n💎На сервере средний уровень отыгрыша РП.\n💎Смены идут по 24 часа, достаточно для воплощения ваших фантазий!\n💎Множество своих уникальных систем, улучшений и разработок!\n💎Постройте шаттл своей мечты, ограничение только ваша фантазия!\n💎Отзывчывая и дружелюбная администрация!\n💎Наш сервер работает на сверхмощном железе со стабильным тикрейтом в 60!\n💎Полная локализация и постоянные обновления!"
cryo_sleep_rejoining = true

[shuttle]
auto_call_time = 1440
auto_call_extension_time = 30

[atmos]
space_wind_max_velocity = 22.0

[salvage]
expedition_failed_cooldown = 600.0

[replay]
client_recording_enabled = false

[viewport]
maximum_width = 26

[server]
id = "frontier_main"
rules_file = "FrontierRuleset"

[infolinks]
bug_report = "https://github.com/Apxumekm0p/Eclipse-New-Frontier/issues/new/choose"
discord    = "https://discord.gg/5J9Q8WuJFd"
#forum      = ""
github     = "https://github.com/Apxumekm0p/Eclipse-New-Frontier"
#patreon    = ""
#website    = ""
#wiki       = ""
#appeal     = ""

[nf14]
publictransit.wait_time = 60.0
respawn.time = 300.0

[eclipse]
restart_when_server_empty = false
start_round_with_no_players = true

[discord]
rich_main_icon_id = "https://shorturl.at/nHmHm"
