[net]
max_connections = 256
pvs_range = 20.0
pvs_priority_range = 30.0
tickrate = 60

[game]
maxplayers = 150
soft_max_players = 100
hostname = "🌒 Project Eclipse - ФРОНТИР! [18+] 🌒"
desc = "Добро пожаловать на сектор Эклипс.\nНа этом сервере средние требования к RP.\n"
cryo_sleep_rejoining = true

[shuttle]
auto_call_time = 1440
auto_call_extension_time = 30

[atmos]
space_wind_max_velocity = 22.0

[salvage]
expedition_failed_cooldown = 600.0

[replay]
client_recording_enabled = false

[viewport]
maximum_width = 26

[server]
id = "frontier_main"
rules_file = "FrontierRuleset"

[infolinks]
bug_report = "https://github.com/Apxumekm0p/Eclipse-New-Frontier/issues/new/choose"
discord    = "https://discord.gg/BH39NH4"
#forum      = ""
github     = "https://github.com/Apxumekm0p/Eclipse-New-Frontier"
#patreon    = ""
#website    = ""
#wiki       = ""
#appeal     = ""

[nf14.respawn]
time = 300.0

[eclipse]
restart_when_server_empty = false
